### ISSUE TITLE
Error due to Datetime(6) on migration MySQL v5

### ISSUE THREAD

**Issue by RichardAtDP** [vapor/mysql-driver#108]
When a migration runs, it tries to create DATETIME fields with the format DATETIME(6). This creates an error in mySQL 5.5.11

Generates Error:
CREATE TABLE `fluent` (`id` BINARY(16)  PRIMARY KEY, `name` VARCHAR(255)  NOT NULL, `batch` BIGINT  NOT NULL, `createdAt` DATETIME(6) , `updatedAt` DATETIME(6) )

Does not Generate Error:
CREATE TABLE `fluent` (`id` BINARY(16)  PRIMARY KEY, `name` VARCHAR(255)  NOT NULL, `batch` BIGINT  NOT NULL, `createdAt` DATETIME , `updatedAt` DATETIME )

**Comment by tanner0101** [comment]
We will probably need a way to disable usage of the higher precision `DATETIME(...)` when MySQL < 5.6 is used.

**Comment by tanner0101** [comment]
Once 3.0.0 is released, the best way to fix this will be to use a custom migration and specify `.datetime(nil)` as the type.
