### ISSUE TITLE
[RC3] Parallel requests no longer permitted?

### ISSUE THREAD

**Issue by jseibert** [vapor/mysql-driver#116]
With the latest RC3 changes, it looks like parallelizing operations is no longer permitted? What is the recommended way to act on an array of object and initiate N database requests?

cc @tanner0101 

![image](https://user-images.githubusercontent.com/80599/41482710-4f154f8e-708b-11e8-8b56-09ae3581d760.png)

**Comment by tanner0101** [comment]
Fixed here: https://github.com/vapor/fluent/pull/507

**Comment by jseibert** [comment]
@tanner0101 just got a chance to test this and it works great, thanks! Closing.
