### ISSUE TITLE
Unable to decode a UUID property stored as a string

### ISSUE THREAD

**Issue by bygri** [vapor/mysql-driver#122]
I am having trouble with a model containing a UUID stored in MySQL as `CHAR` not `BINARY`.

```sql
`uuid` CHAR(36) NOT NULL
```

This implementation stores the property as a UUID, and uses custom encode/decode methods to
fetch and store the UUID as a string. Encoding works fine, the table contains the UUID correctly,
but decoding fails. Fetching the UUID as a string always returns the literal string `"0"`.
```swift
final class FailModel: MySQLModel {
  var uuid: UUID

  enum CodingKeys: String, CodingKey {
    case uuid = "uuid"
  }

  init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    let uuidString: String = try container.decode(String.self, forKey: .uuid)
    uuid = UUID(uuidString)! // fails here. Decoded `uuidString` is the literal string "0".
  }

  func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(uuid.uuidString, forKey: .uuid)
  }
}
```

This implementation stores the property as a string, and adds a function to forcibly convert
it to a UUID as needed. It works.
```swift
final class SuccessModel: MySQLModel {
  var uuidString: String

  func uuid() -> UUID {
    return UUID(uuidString)!
  }

  enum CodingKeys: String, CodingKey {
    case uuidString = "uuid"
  }

  init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    uuidString = try container.decode(String.self, forKey: .uuidString)
  }

  func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(uuidString, forKey: .uuidString)
  }
}
```

I suspect the first version doesn't work because the CodingKey points to a
UUID property and even though I am telling the decoder to decode a String,
Fluent has already populated the decoder with binary UUID data. Is that true?

While the latter version works, it feels like a regression against Vapor 2 where
the model did not have to exactly reflect the database table structure, and custom
logic could be used in the load/save methods to transform between the two.

**Comment by tanner0101** [comment]
Sorry this one slipped through the cracks. This does likely have to do with how reflection is working in Fluent 3. Fluent 4 no longer uses Codable-based reflection so this should no longer be a problem.

Here's some code that achieves a similar effect using Fluent 4's API:

```swift
final class Foo: Model {
    static let schema = "foos"

    @ID(key: .id)
    var id: UUID?

    @Field(key: "bar")
    var _bar: String

    var bar: UUID {
        get {
            UUID(uuidString: self._bar)!
        }
        set {
            self._bar = newValue.uuidString
        }
    }

    init() { }

    init(id: UUID? = nil, bar: UUID) {
        self.id = id
        self.bar = bar
    }
}

// migration
database.schema("foos")
    .id()
    .field("bar", .sql(raw: "CHAR(36)"), .required)
    .create()
```
