### ISSUE TITLE
Immediate failure on transaction use

### ISSUE THREAD

**Issue by bygri** [vapor/mysql-driver#136]
This code:

```swift
return conn.transaction(on: .mysql) { txn in
  return MyObject.query(on: txn).all()
}
```

throws [this error](https://github.com/vapor/mysql/blob/master/Sources/MySQL/Connection/MySQLConnection.swift#L81):

```
NIO-ELT-#1 (2): Fatal error: Attempting to call `send(...)` while handler is still: callback(NIO.EventLoopPromise<()>(futureResult: NIO.EventLoopFuture<()>), (Function)).
```

on MySQL database version 5.7, using Vapor 3.1.0, Fluent 3.1.2, FluentMySQL 3.0.1.

The same code executed without transactions works fine.

**Comment by sofbix** [comment]
I aggrieved that is reproducing, but I am thinking it depended on MySQL lib (tested on 3.2.4)
My case is better:
We has 2 async query in the transaction and one should throw error.

Example:

```
return request.transaction(on: .mysql) { (connect) -> Future<SuccessResponse> in

  let userFuture : Future<Void> = UserEntity.find(updateUserId, on: connect).map { entity in
    throw Abort(.forbidden, reason: "You have not access")
  }

  let userPersonalFuture : Future<Void> = UserPersonalEntity.find(currentUser.userId, on: connect).map {}

  return [userFuture, userPersonalFuture].flattern(on: connect).map {
    return SuccessResponse()
  }

}
```

That generated:

```
Fatal error: Attempting to call `send(...)` while handler is still: callback(NIO.EventLoopPromise<()>(futureResult: NIO.EventLoopFuture<()>), (Function)).: file /.build/checkouts/mysql/Sources/MySQL/Connection/MySQLConnection.swift, line 81
```

If would removed request.transaction and use request without connect then it works is fine

**Comment by lukeify** [comment]
Also experiencing this error. Effectively we can't use transactions with MySQL in Vapor?

**Comment by tanner0101** [comment]
This limitation has been lifted in the latest version of the driver (4.0.0) as `MySQLConnection` now supports queueing up multiple queries.
