### ISSUE TITLE
mysql error reading communication packets

### ISSUE THREAD

**Issue by gentges** [vapor/mysql-driver#138]
Lately I get weird errors in mysql when trying to save entries to the database or during migration at startup:
```
Fatal error: raised on top level: connectFailed(NIO.NIOConnectionError(host: "db", port: 3306, dnsAError: Optional(NIO.SocketAddressError.unknown(host: "db", port: 3306)), dnsAAAAError: Optional(NIO.SocketAddressError.unknown(host: "db", port: 3306)), connectionErrors: [])): file /usr/local/api/Sources/Run/main.swift, line 8
```

I am running mysql 5.7 in a docker container.
Mysql logs:
`[Note] Aborted connection 3 to db: 'daily-diary' user: 'api' host: '10.0.12.4' (Got an error reading communication packets)`

When logging the queries and searching for the given connection I found out that it never quits, so maybe that causes the problem.
```
2 Quit	
3 Connect	***@*** on *** using TCP/IP
3 Prepare	INSERT INTO `User` (`email`, `passwordHash`, `username`) VALUES (?, ?, ?)
3 Execute	INSERT INTO `User` (`email`, `passwordHash`, `username`) VALUES ('***', '***', '***')
3 Close stmt	
4 Connect	***@*** on *** using TCP/IP
```

But I only have these problems when running the api and database in docker as a stack. On my Mac with the same mysql version I never experienced the problem. The configuration should be the same, because I compared the mysql vars on both instances.

**Comment by tanner0101** [comment]
> When logging the queries and searching for the given connection I found out that it never quits, so maybe that causes the problem.

Connections staying open is expected, all connections used by Fluent are kept open in a pool so that they can be re-used.

> `dnsAError: Optional(NIO.SocketAddressError.unknown(host: "db", port: 3306)`

Seems like a network failure when attempting to create a new connection.
