### ISSUE TITLE
Unable to remove constraints in update

### ISSUE THREAD

**Issue by siemensikkema** [vapor/mysql-driver#148]
On version 3.0.2 when doing 
```swift
return Database.update(Product.self, on: conn) { updater in
  updater.deleteConstraint(.constraint(.notNull, .keyPath(\Product.someProperty)))
}
```
No statement to delete the constraint is created: ``ALTER TABLE `Product`  []``

The `deleteConstraints` value from `FluentMySQLSchema` is not copied to `MySQLAlterTable` [here](https://github.com/vapor/fluent-mysql-driver/blob/a67a5761859d19dc3e24563f9ab08b4a533adb48/Sources/FluentMySQL/MySQLDatabase%2BSchemaSupporting.swift#L73) as there is no such property on that struct.

This issue is similar to https://github.com/vapor/fluent-mysql-driver/pull/147

**Comment by tanner0101** [comment]
thanks @siemensikkema !
fixed here: https://github.com/vapor/fluent-mysql-driver/releases/tag/3.1.0
