### ISSUE TITLE
Add Socket option in Custom MySQL Configuration

### ISSUE THREAD

**Issue by anmolrajpal** [vapor/mysql-driver#161]
Though there are abundant configuration options in the current version, however, I want to use a custom socket for my configuration. As I am using MAMP, it runs MySQL with a custom configuration with a custom socket => `/Applications/MAMP/tmp/mysql/mysql.sock`
Other Server Side Swift Frameworks such as Perfect Swift provides this 'Socket' option. 
I hope this option will be added in Vapor too.

**Comment by tanner0101** [comment]
Related to https://github.com/vapor/postgres-kit/pull/170
