### ISSUE TITLE
MySQL & MAMP/Docker

### ISSUE THREAD

**Issue by josepfm** [vapor/mysql-driver#169]
Hi,

I'm trying to connect to the database mounted on MAMP and I can't get it.

Attached are the configuration and error codes for Xcode.

Fatal error: Error raised at top level: connection reset (error set): Connection refused (errno: 61): file /AppleInternal/BuildRoot/Library/Caches/com.apple.xbs/Sources/swiftlang/swiftlang-1103.8.25.8/swift/stdlib/public/core/ErrorType.swift, line 200
2020-04-22 18:44:26.894845+0200 Run[13593:475784] 
<img width="1472" alt="Captura de pantalla 2020-04-22 a las 18 49 00" src="https://user-images.githubusercontent.com/8105593/80010002-13487f80-84ca-11ea-9cdf-ed4466da215b.png">
Fatal error: Error raised at top level: connection reset (error set): Connection refused (errno: 61): file /AppleInternal/BuildRoot/Library/Caches/com.apple.xbs/Sources/swiftlang/swiftlang-1103.8.25.8/swift/stdlib/public/core/ErrorType.swift, line 200

And I've tried both of these configurations.

    app.databases.use(.mysql(hostname: "localhost", port: 8889, username: "root", password: "", database: "name_database", tlsConfiguration: nil, maxConnectionsPerEventLoop: 1), as: .mysql)
    
        
//    app.databases.use(.mysql(
//        hostname: "localhost",
//        username: "root",
//        password: "",
//        database: "name_database"
//    ), as: .mysql)

**Comment by tanner0101** [comment]
Are you able to connect with a client like Sequel pro using the same hostname, port, credentials, and TLS configuration?

**Comment by josepfm** [comment]
> Are you able to connect with a client like Sequel pro using the same hostname, port, credentials, and TLS configuration?

As you can see in the screenshot, MAMP incorporates a direct access to Sequel (the icon in the image).

By clicking on it, the program opens with the access data set and you can access the databases you have.

**Comment by josepfm** [comment]
> > Are you able to connect with a client like Sequel pro using the same hostname, port, credentials, and TLS configuration?
> 
> As you can see in the screenshot, MAMP incorporates a direct access to Sequel (the icon in the image).
> 
> By clicking on it, the program opens with the access data set and you can access the databases you have.

I don't think it's a MAMP problem in this case, because I can't connect to Docker or my database hosted on my own DigitalOcean server either.

**Comment by tanner0101** [comment]
I did a quick StackOverflow search and it looks like you may need to connect using this unix domain socket path: `/Applications/MAMP/tmp/mysql/mysql.sock`. 

```swift
app.databases.use(.mysql(unixDomainSocketPath:...))
```

> https://stackoverflow.com/questions/1391182/how-to-connect-mysql-workbench-with-mamp-pro

Not sure though, I've never used MAMP before. If you can figure out how to connect to it via any other client (like Sequel Pro _without_ having the MAMP app do it for you) then the same method should work via Vapor.

**Comment by josepfm** [comment]
I finally managed to make it work.

I used the following configuration plus remote access from inside MAMP.

app.databases.use(.mysql(hostname: , port: , username: , password: , database: , tlsConfiguration: nil, maxConnectionsPerEventLoop: 1), as: .mysql)
