### ISSUE TITLE
`.string` migrations results in a 256 length varchar

### ISSUE THREAD

**Issue by 0xTim** [vapor/mysql-driver#171]
When setting up a `.string` column in MySQL (e.g. [here](https://github.com/brokenhandsio/steampress-fluent/blob/master/Sources/SteampressFluent/Models/BlogPost%2BFluent.swift#L72)), the column is created as `VARCHAR(256)` instead of anything longer. I remember a discussion on Discord about making this longer, but it doesn't appear to be the case

**Comment by tanner0101** [comment]
Fluent 4 continues to use `VARCHAR(255)` like Fluent 3 did. I don't remember the discussion about this in Discord, what was the reason behind changing that again? 

For reference:

- Fluent 4: https://github.com/vapor/fluent-mysql-driver/blob/master/Sources/FluentMySQLDriver/MySQLConverterDelegate.swift#L6
- Fluent 3: https://github.com/vapor/mysql-kit/blob/3/Sources/MySQL/SQL/MySQLDataTypeStaticRepresentable.swift#L24
