### ISSUE TITLE
It can't be decoded if value is null

### ISSUE THREAD

**Issue by mohok** [vapor/mysql-driver#182]
When I query using raw query, it can't be decoded to optional variable if value is null. 

Should I insert `IFNULL` and default value to query? How to decode as nil?

* error response
```
"Value of type 'Int' required for key ''."
```

**Comment by tanner0101** [comment]
Hi @mohok, thanks for reporting this issue. Please include the version of the package you are using as well as information to help reproduce like the query string, table schema, and row values. We can reopen once we have this info.
