### ISSUE TITLE
Not able to store special characters and emojis properly

### ISSUE THREAD

**Issue by diegotl** [vapor/mysql-driver#184]
I'm rewriting an old API build with Vapor 2 to Vapor 4. But this time I can't seem to store accents, special characters and emojis properly. I have the table encoding and collation set to utf8mb4 but still, when seeing from Sequel, I see them like "ChapÃ©u ðŸŽ“".

Is there a way to fix it currently? Thanks

**Comment by tanner0101** [comment]
As far as I know, this is determined by the MySQL server. MySQLNIO is already specifying `utf8mb4` as the desired character set: https://github.com/vapor/mysql-nio/blob/master/Sources/MySQLNIO/MySQLConnectionHandler.swift#L160

Double check your database is using `utf8mb4` and `utf8mb4_unicode_ci` and that everything was converted correctly.
