### ISSUE TITLE
Make `MySQLConfiguration` non-constant

### ISSUE THREAD

**Issue by 0xTim** [vapor/mysql-driver#211]
We should allow the configuration in `MySQLConfiguration` to be changed by changing the properties to `var`s. This matches Postgres and makes it easier to set things like the `TLSConfiguration`

**Comment by lodenrogue** [comment]
I can give this a try

**Comment by lodenrogue** [comment]
PR: https://github.com/vapor/fluent-mysql-driver/pull/212

Please review it. I've never worked with swift before and I have no way to test locally.

**Comment by fananek** [comment]
I’m afraid you edited wrong file. Issue is about `MySQLConfiguration` [properties](https://github.com/vapor/mysql-kit/blob/529bde8ce86c8a2546e7e8856c206f3358dff41e/Sources/MySQLKit/MySQLConfiguration.swift#L6-L10).

All these `let`s shall be changed to `var`s.

**Comment by lodenrogue** [comment]
Got it. I'll make that change

**Comment by lodenrogue** [comment]
PR: https://github.com/vapor/mysql-kit/pull/309

I think a better approach is to just create a new MySQLConfiguration object and keep the fields immutable. But here's the change you requested in case you still want it.

**Comment by 0xTim** [comment]
Fixed in https://github.com/vapor/mysql-kit/pull/309
