### ISSUE TITLE
Connection refused (errno: 61) when trying to connect to a remote Database

### ISSUE THREAD

**Issue by VanegasDev** [vapor/mysql-driver#220]
I am trying to connect to a remote Database, and I am getting this error
{"error":true,"reason":"connection reset (error set): Connection refused (errno: 61)"}

This is my configuration
```
    app.databases.use(.mysql(
        hostname: Environment.get("IP") ?? "localhost",
        port: Environment.get("PORT").flatMap(Int.init(_:)) ?? MySQLConfiguration.ianaPortNumber,
        username: Environment.get("USERNAME") ?? "vapor_username",
        password: Environment.get("PASS") ?? "vapor_password",
        database: Environment.get("DB") ?? "vapor_database",
        tlsConfiguration: nil
    ), as: .mysql)
```

I've already tried this credentials using MySQL Workbench and the connection is taking place correctly, but when I run my Vapor App it returns me the error from above

**Comment by 0xTim** [comment]
Few questions:

* how are you running the Vapor app?
* is it the same machine as MySQL workbench (and not via docker etc)
* have you verified the environment variables are being set correctly?

**Comment by VanegasDev** [comment]
Thank you so much, the password environment variable wasn't set correctly
