### ISSUE TITLE
Linux Tests

### ISSUE THREAD

**Issue by BrettRToomey** [vapor/mysql-driver#23]
I noticed that someone's PR failed on Mac but not on Linux. I was really confused as it's usually the opposite. I looked into it and it looks like Linux is only running one of the test cases, not all three. Is there a specific reason for this?

https://github.com/vapor/mysql-driver/blob/master/Tests/LinuxMain.swift#L7

**Comment by Casperhr** [comment]
Added linux tests https://github.com/vapor/mysql-driver/pull/24
