### ISSUE TITLE
Remove ambiguous `date(_:optional:unique:default:)`

### ISSUE THREAD

**Issue by kdawgwilk** [vapor/mysql-driver#34]
## Environment
```
Vapor       : 2.0.0-beta.1
MySQLDriver : 2.0.0-beta.1
Swift       : 3.1
Xcode       : 8.3
```
## Report
I got this compiler error:
```
Ambiguous use of 'date(_:optional:unique:default:)'
Found this candidate (Fluent.Builder)
Found this candidate (MySQLDriver.Builder)
```
when trying to compile this line:
```swift
builder.date("completed_on", optional: true)
```

**Comment by tanner0101** [comment]
Fixed! https://github.com/vapor/mysql-driver/releases/tag/2.0.0-beta.2

**Comment by kdawgwilk** [comment]
Would this also be an issue for other field types? At a quick glance`int` seemed like it existed in both places as well

**Comment by tanner0101** [comment]
It's `integer` in this package so shouldn't be an issue
