### ISSUE TITLE
redundant conformance constraint 'E': 'Entity'

### ISSUE THREAD

**Issue by niklassaers** [vapor/mysql-driver#47]
"swift test" gives these four warnings:

Compile Swift Module 'MySQLDriver' (4 sources)
mysql-driver-master/Sources/MySQLDriver/MySQLConnection.swift:25:26: warning: redundant conformance constraint 'E': 'Entity'
    public func query<E: Entity>(_ query: RawOr<Query<E>>) throws -> Node {
                         ^
mysql-driver-master/Sources/MySQLDriver/MySQLConnection.swift:25:43: note: conformance constraint 'E': 'Entity' inferred from type here
    public func query<E: Entity>(_ query: RawOr<Query<E>>) throws -> Node {
                                          ^
mysql-driver-master/Sources/MySQLDriver/MySQLConnection.swift:25:26: warning: redundant conformance constraint 'E': 'Entity'
    public func query<E: Entity>(_ query: RawOr<Query<E>>) throws -> Node {
                         ^
mysql-driver-master/Sources/MySQLDriver/MySQLConnection.swift:25:43: note: conformance constraint 'E': 'Entity' inferred from type here
    public func query<E: Entity>(_ query: RawOr<Query<E>>) throws -> Node {

**Comment by Joannis** [comment]
Swift 4 creates more warnings for redundant conformances that can be automatically inferred. I'm not sure if Swift 3 can infer them at all, though. Definitely something to fix, but I hope it's easily achievable.

**Comment by tanner0101** [comment]
Will require a ton of `#if swift(>=4)` :(
