### ISSUE TITLE
Custom column representables support

### ISSUE THREAD

**Issue by rafiki270** [vapor/mysql-driver#56]
```swift
extension MyCustomType: MySQLColumnTypeRepresentable { 
    static var mysqlColumnType: MySQL.ColumnType { return .varChar(64) } 
}
```
(Before it get's deleted: https://qutheory.slack.com/archives/C4QRYJ6DD/p1515520041000182 )

**Comment by vzsg** [comment]
Here's a permanent link to (a neighbor of) that message: [Archive](https://qutheory.slackarchive.io/beta/page-99/ts-1515520009000429)

**Comment by tanner0101** [comment]
This has been added 👍
