### ISSUE TITLE
Schema generator crash on enum values V3

### ISSUE THREAD

**Issue by rafiki270** [vapor/mysql-driver#58]
`MySQLDatabase+Schema.swift` doesn't handle `KeyStringDecodable`'s raw values and crashes in `public static func fieldType(for type: Any.Type) throws -> ColumnType`

**Comment by tanner0101** [comment]
I'm pretty sure this has been fixed now (or at least a clearer error message) with recent updates to core. Please re-open if you continue to see it! Thanks
