### ISSUE TITLE
multiple query start same time

### ISSUE THREAD

**Issue by tanner0101** [vapor/mysql-driver#60]
for some reason one of the following snippets works and the other does not

does not work:
```swift
func acronymHandler(_ req: Request) throws -> Future<View> {
    return try req.parameter(Acronym.self).flatMap(to: View.self) { acronym in
        return try flatMap(to: View.self, acronym.creator.get(on: req), acronym.categories.query(on: req).all()) { creator, categories in
            let context = AcronymContext(title: acronym.long, acronym: acronym, creator: creator, categoires: categories)
            return try req.leaf().render("acronym", context)
        }
    }
}
```

works:
```swift
func acronymHandler(_ req: Request) throws -> Future<View> {
        return try req.parameter(Acronym.self).flatMap(to: View.self) { acronym in
            return acronym.creator.get(on: req).flatMap(to: View.self) { creator in
                return try acronym.categories.query(on: req).all().flatMap(to: View.self) { categories in
                    let context = AcronymContext(title: acronym.long, acronym: acronym, creator: creator, categoires: categories)
                    return try req.leaf().render("acronym", context)

                }
            }
        }
    }
```
thinking maybe this is caused by MySQL not supporting _starting_ two queries at once?

**Comment by tanner0101** [comment]
This still seems to be an issue. MySQL state machine blows up if two queries are started at the same time.

**Comment by 0xTim** [comment]
Yep just retested this and hit the same issue

**Comment by Joannis** [comment]
Shouldn't the `PushStream` prevent the 2 queries from being executed at the same time?

**Comment by 0xTim** [comment]
So hitting this in another place that wasn't happening before when doing `return try flatMap(to: HTTPStatus.self, req.parameter(Acronym.self), req.parameter(Category.self)) { acronym, category in` - this returns the error `[ ERROR ] FluentError.modelNotFound: No model with ID 1 was found (Model.swift:267)`
An important thing to note is that any subsequent requests **never** get fulfilled, every one just hangs and times out, even simple Fluent `.all()` functions
I'm assuming this is all about to be rewritten with the NIO changes however!
