### ISSUE TITLE
Support of emojis?

### ISSUE THREAD

**Issue by agordeev** [vapor/mysql-driver#61]
I'm getting this error when trying to store a string containing emojis:

MySQL error occured while saving: MySQL Error: Incorrect string value: '\xF0\x9F\x92\x93\xF0\x9F...' for column 'description' at row 1

Identifier: MySQL.MySQLError.1366 (truncatedWrongValueForField)

If I perform a raw query, it inserts a row just fine:

```
if let mysqlDriver = drop.database?.driver as? MySQLDriver.Driver {
    try! mysqlDriver.raw("INSERT INTO countries (uValue, createdAt, updatedAt) VALUES ('Test 💓💓', '2008-7-04', '2008-7-04')")
}
```

My database seems properly set for storing emojis:

```
SHOW VARIABLES WHERE Variable_name LIKE 'character\_set\_%' OR Variable_name LIKE 'collation%';

character_set_client	utf8mb4
character_set_connection	utf8mb4
character_set_database	utf8
character_set_filesystem	binary
character_set_results	utf8mb4
character_set_server	utf8
character_set_system	utf8
collation_connection	utf8mb4_general_ci
collation_database	utf8_general_ci
collation_server	utf8_general_ci
```

How to fix the issue? MySQL Driver version is `2.0.3`

**Comment by tanner0101** [comment]
This is fixed in version in 3.0. Just make sure to use the parameterized protocol (`query` instead of `simpleQuery`). Thanks :)
