### ISSUE TITLE
Cannot convert value of type 'TCPSocketSource' to expected argument type 'SocketSource<_>'

### ISSUE THREAD

**Issue by MihaelIsaev** [vapor/mysql-driver#62]
I added FluentMySQL to my Vapor 3 beta project and now I can't build it because of error

```swift
Cannot convert value of type 'TCPSocketSource' to expected argument type 'SocketSource<_>'
```

<img width="2032" alt="2018-02-01 1 20 23" src="https://user-images.githubusercontent.com/1272610/35648128-1a6171ac-06ee-11e8-88be-c0d6be114165.png">

Is there any way to fix it?

**Comment by tanner0101** [comment]
This has been fixed
