### ISSUE TITLE
Support for JSON

### ISSUE THREAD

**Issue by anthonycastelli** [vapor/mysql-driver#69]
Looking at the current Vapor 3 PostgreSQL driver, it supports the JSON field. MySQL does support JSON and it would be nice to support this field in a similar manner to the PostgreSQL version to keep things simple across the drivers. 

What I'm referring to is this: https://github.com/twof/VaporNation/blob/master/week0-18-01-21.md#postgresql-support-for-jsonjsonb-and-arrays @twof has put together this example.

**Comment by tanner0101** [comment]
Totally agree! Closing in favor of https://github.com/vapor/fluent-mysql/issues/72
