### ISSUE TITLE
MySQLError.tooManyParametersBound

### ISSUE THREAD

**Issue by zerausolrac** [vapor/mysql-driver#78]
MySQLError.tooManyParametersBound: More parameters were bound than specified in the query (PreparedStatement.swift:86)

//Package
      ```  .package(url: "https://github.com/vapor/vapor.git", from: "3.0.0-rc.1.1"),
        .package(url: "https://github.com/vapor/fluent-mysql", from: "3.0.0-rc.1.1"),
        .package(url: "https://github.com/vapor/leaf.git", from:"3.0.0-rc.1"),
        .package(url:"https://github.com/vapor/auth.git", from:"2.0.0-rc"),  ```


//Model 

```
 final class User:Codable, CustomStringConvertible {
    var description: String {
        return "\(String(describing: self.username)), \(self.password), \(String(describing: createdAt)) \(String(describing: updatedAt))"
    } 
    
    
   
    var username:String?
    var password:String
    var createdAt: Date?
    var updatedAt: Date?
    
init( username:String?=nil, password:String) {
        //self.id = id
        self.username = username
        self.password = password
    }

}

extension User: Model,Timestampable {
    public static var createdAtKey: CreatedAtKey {return \.createdAt }
    public static var updatedAtKey: UpdatedAtKey { return \.updatedAt}

    typealias Database = MySQLDatabase
    
    public typealias ID = String
    public static var idKey: IDKey{ return \.username }
    

}

extension User: Migration {
    public static func prepare(on connection: Database.Connection) -> Future<Void> {
        return Database.create(self, on: connection, closure: { (builder) in
            try builder.field(for: \User.username)
            try builder.field(for: \User.password)
            try builder.field(for: \User.createdAt)
            try builder.field(for: \User.updatedAt)
        })
    }
}

extension User: Content { }
extension User: Parameter { }  
```


//Controller 

```  
final class UserController {
    func crear(_ req: Request) throws -> Future<User> {
     return try req.content.decode(User.self).flatMap(to: User.self) { user in
        
        return user.save(on: req)
    }
 }
}  
```


//Route 

```   
public func routes(_ router: Router) throws {
    let userController = UserController()
    router.post("crear", use:userController.crear)
    
}  
 ```

**Comment by tanner0101** [comment]
This was fixed during the RC.2 refactor, thanks!
