### ISSUE TITLE
ColumnType VARCHAR BINARY

### ISSUE THREAD

**Issue by Mladen-K** [vapor/mysql-driver#81]
When "BINARY" is added as attribute to ColumnType name: "VARCHAR", target field in db is assigned base "VARCHAR" type instead of "BINARY".

MySQL database is provided by AWS - RDS.

I'm using:
```swift
builder.field(type: .varChar(length: 32, binary: true), for: \.id)
```

**Comment by tanner0101** [comment]
this will be fixed in rc.2. thanks!
