### ISSUE TITLE
Generated index names are almost always too long

### ISSUE THREAD

**Issue by jseibert** [vapor/mysql-driver#89]
In MySQL, index names must be 64 characters or less. However, FluentMySQL does not enforce or prepare for this, causing fatal errors:

```
Migrating mysql DB
⚠️ [MySQLError.server (1059): Identifier name '_fluent_index_financial_accounts_financialProviderId_plaidAccountId' is too long] [/Users/jseibert/api/.build/checkouts/mysql.git-1890032512239690518/Sources/MySQL/Connection/MySQLConnection.swift:42:69]
Program ended with exit code: 1
```

SchemaIndex should support manually overriding the name, or it should change to a more intelligent name synthesis scheme.

**Comment by tanner0101** [comment]
Same issue with foreign key names. Related to https://github.com/vapor/fluent-mysql/issues/94. Going to try hashing them.

**Comment by jseibert** [comment]
👍
