### ISSUE TITLE
`property ~~ []` SQL Syntax is Broken

### ISSUE THREAD

**Issue by calebkleveter** [vapor/mysql-driver#98]
When you try run a query that gets models based on the elements in an array and the array is empty, like this:

```swift
MyModel.query(on: request).filter(\.id ~~ [])
```

Instead of generating a `WHERE (false)` statement, it creates 

```sql
WHERE (`mymodels`.`id` false)
```

**Comment by tanner0101** [comment]
This has been fixed and a test added in #114
