### ISSUE TITLE
add MySQLEnum type

### ISSUE THREAD

**Issue by tanner0101** [vapor/mysql-driver#99]

**Comment by tanner0101** [comment]
Varchar and tiny int versions

**Comment by grahamburgsma** [comment]
Would also be nice to support the actual ENUM type.

Quoting some advantages from the docs:
- Compact data storage in situations where a column has a limited set of possible values. The strings you specify as input values are automatically encoded as numbers.
- Readable queries and output. The numbers are translated back to the corresponding strings in query results.
https://dev.mysql.com/doc/refman/5.7/en/enum.html

This would be ideal over faking it with varchat and tiny int as you get both the compact storage and readable output in the database and your json responses.
